In [2]:
import pandas as pd # import Pandas as pd to use it .

In [3]:
df = pd.read_csv('data/survey_results_public.csv', index_col='ResponseId') # read the public csv file 
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col='qname') # read the result schema .csv.

In [4]:
df

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83435,I am a developer by profession,Employed full-time,United States of America,Texas,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,5,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,160500.0
83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,2,...,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,3960.0
83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,4,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0
83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,3,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0
83439,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,4,...,18-24 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0

In [5]:
df.shape # number of Columns and Rows .

(83439, 47)

In [6]:
df.info # Information of the data frame .

<bound method DataFrame.info of                                                    MainBranch  \
ResponseId
1                              I am a developer by profession
2                      I am a student who is learning to code
3           I am not primarily a developer, but I write co...
4                              I am a developer by profession
5                              I am a developer by profession
...                                                       ...
83435                          I am a developer by profession
83436                          I am a developer by profession
83437                          I am a developer by profession
83438                          I am a developer by profession
83439                          I am a developer by profession

                                                   Employment  \
ResponseId
1           Independent contractor, freelancer, or self-em...
2                                          Student, full-time
3                                          Student, full-time
4                                          Employed full-time
5           Independent contractor, freelancer, or self-em...
...                                                       ...
83435                                      Employed full-time
83436       Independent contractor, freelancer, or self-em...
83437                                      Employed full-time
83438                                      Employed full-time
83439                                      Employed full-time

                                                      Country    US_State  \
ResponseId
1                                                    Slovakia         NaN
2                                                 Netherlands         NaN
3                                          Russian Federation         NaN
4                                                     Austria         NaN
5           United Kingdom of Great Britain and Northern I...         NaN
...                                                       ...         ...
83435                                United States of America       Texas
83436                                                   Benin         NaN
83437                                United States of America  New Jersey
83438                                                  Canada         NaN
83439                                                  Brazil         NaN

           UK_Country                                            EdLevel  \
ResponseId
1                 NaN  Secondary school (e.g. American high school, G...
2                 NaN       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
3                 NaN       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4                 NaN    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
5             England    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
...               ...                                                ...
83435             NaN       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
83436             NaN       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
83437             NaN  Secondary school (e.g. American high school, G...
83438             NaN       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
83439             NaN                 Professional degree (JD, MD, etc.)

               Age1stCode                                          LearnCode  \
ResponseId
1           18 - 24 years  Coding Bootcamp;Other online resources (ex: vi...
2           11 - 17 years  Other online resources (ex: videos, blogs, etc...
3           11 - 17 years  Other online resources (ex: videos, blogs, etc...
4           11 - 17 years                                                NaN
5            5 - 10 years                            Friend or family member
...                   ...                                                ...
83435       11 - 17 years  Other online resources (ex: videos, blogs, etc...
83436       11 - 17 years  Other online resources (ex: videos, blogs, etc...
83437       11 - 17 years                                             School
83438       11 - 17 years  Online Courses or Certification;Books / Physic...
83439       11 - 17 years                                             School

           YearsCode YearsCodePro  ...              Age Gender Trans  \
ResponseId                         ...
1                NaN          NaN  ...  25-34 years old    Man    No
2                  7          NaN  ...  18-24 years old    Man    No
3                NaN          NaN  ...  18-24 years old    Man    No
4                NaN          NaN  ...  35-44 years old    Man    No
5                 17           10  ...  25-34 years old    Man    No
...              ...          ...  ...              ...    ...   ...
83435              6            5  ...  25-34 years old    Man    No
83436              4            2  ...  18-24 years old    Man    No
83437             10            4  ...  25-34 years old    Man    No
83438              5            3  ...  25-34 years old    Man    No
83439             14            4  ...  18-24 years old    Man    No

                          Sexuality                     Ethnicity  \
ResponseId
1           Straight / Heterosexual  White or of European descent
2           Straight / Heterosexual  White or of European descent
3                 Prefer not to say             Prefer not to say
4           Straight / Heterosexual  White or of European descent
5                               NaN  White or of European descent
...                             ...                           ...
83435       Straight / Heterosexual  White or of European descent
83436       Straight / Heterosexual   Black or of African descent
83437                           NaN  White or of European descent
83438       Straight / Heterosexual  White or of European descent
83439       Straight / Heterosexual        Hispanic or Latino/a/x

                          Accessibility  \
ResponseId
1                     None of the above
2                     None of the above
3                     None of the above
4           I am deaf / hard of hearing
5                     None of the above
...                                 ...
83435                 None of the above
83436                 None of the above
83437                 None of the above
83438                 None of the above
83439                 None of the above

                                                 MentalHealth  \
ResponseId
1                                           None of the above
2                                           None of the above
3                                           None of the above
4                                                         NaN
5                                                         NaN
...                                                       ...
83435       I have a concentration and/or memory disorder ...
83436                                       None of the above
83437                                       None of the above
83438       I have a mood or emotional disorder (e.g. depr...
83439                                       None of the above

                     SurveyLength                  SurveyEase  \
ResponseId
1           Appropriate in length                        Easy
2           Appropriate in length                        Easy
3           Appropriate in length                        Easy
4           Appropriate in length  Neither easy nor difficult
5           Appropriate in length                        Easy
...                           ...                         ...
83435       Appropriate in length                        Easy
83436       Appropriate in length                        Easy
83437       Appropriate in length  Neither easy nor difficult
83438       Appropriate in length  Neither easy nor difficult
83439       Appropriate in length                        Easy

           ConvertedCompYearly
ResponseId
1                      62268.0
2                          NaN
3                          NaN
4                          NaN
5                          NaN
...                        ...
83435                 160500.0
83436                   3960.0
83437                  90000.0
83438                 816816.0
83439                  21168.0

[83439 rows x 47 columns]>

In [7]:
clear

In [8]:
df.columns

Index(['MainBranch', 'Employment', 'Country', 'US_State', 'UK_Country',
       'EdLevel', 'Age1stCode', 'LearnCode', 'YearsCode', 'YearsCodePro',
       'DevType', 'OrgSize', 'Currency', 'CompTotal', 'CompFreq',
       'LanguageHaveWorkedWith', 'LanguageWantToWorkWith',
       'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith',
       'PlatformHaveWorkedWith', 'PlatformWantToWorkWith',
       'WebframeHaveWorkedWith', 'WebframeWantToWorkWith',
       'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith',
       'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'OpSys',
       'NEWStuck', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'NEWOtherComms', 'Age', 'Gender', 'Trans', 'Sexuality',
       'Ethnicity', 'Accessibility', 'MentalHealth', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [9]:
pd.set_option('display.max_columns', 15) # max columns to display | set to 15

In [10]:
pd.set_option('display.max_columns', 48) # set the option to see all the columns .
pd.set_option('display.max_rows', 47) # set the option to see all the rows .

In [11]:
df

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,"Developer, mobile",20 to 99 employees,EUR European Euro,4800.0,Monthly,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,PostgreSQL;SQLite,SQLite,NaN,NaN,Laravel;Symfony,NaN,NaN,NaN,NaN,NaN,PHPStorm;Xcode,Atom;Xcode,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,NaN,Cordova,NaN,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,SQLite,SQLite,Heroku,NaN,Flask,Flask,NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,NaN,IPython/Jupyter;PyCharm;RStudio;Sublime Text;V...,IPython/Jupyter;RStudio;Sublime Text;Visual St...,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",Yes,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,"Developer, front-end",100 to 499 employees,EUR European Euro,NaN,Monthly,JavaScript;TypeScript,JavaScript;TypeScript,NaN,NaN,NaN,NaN,Angular;jQuery,Angular;jQuery,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Neutral,No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",GBP\tPound sterling,NaN,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Elasticsearch;PostgreSQL;Redis,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,NaN,Flask,Flask,Apache Spark;Hadoop;NumPy;Pandas,Hadoop;NumPy;Pandas,Docker;Git;Kubernetes;Yarn,Docker;Git;Kubernetes;Yarn,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim;Vis...,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83435,I am a developer by profession,Employed full-time,United States of America,Texas,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,5,"Developer, back-end",20 to 99 employees,USD\tUnited States dollar,160500.0,Yearly,Clojure;Kotlin;SQL,Clojure,Oracle;SQLite,SQLite,AWS,AWS,NaN,NaN,NaN,NaN,Docker;Git,Git;Kubernetes,IntelliJ;Sublime Text;Vim;Visual Studio Code,Sublime Text;Vim,MacOS,Call a coworker or friend;Google it,Stack Overflow;Stack Exchange,A few times per week,No,NaN,"No, not at all",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,160500.0
83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,2,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",XOF\tWest African CFA franc,200000.0,Monthly,NaN,NaN,Firebase;MariaDB;MySQL;PostgreSQL;Redis;SQLite,Firebase;MariaDB;MongoDB;MySQL;PostgreSQL;Redi...,NaN,NaN,Django;jQuery;Laravel;React.js;Ruby on Rails,Django;Express;jQuery;Laravel;React.js;Ruby on...,Flutter;Qt,NaN,Git;Unity 3D;Unreal Engine,Docker;Git;Kubernetes,Android Studio;Eclipse;Emacs;IntelliJ;NetBeans...,Emacs;IntelliJ;PHPStorm;PyCharm;RStudio;Sublim...,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",No,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,3960.0
83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,4,Data scientist or machine learning specialist;...,"10,000 or more employees",USD\tUnited States dollar,1800.0,Weekly,Groovy;Java;Python,Java;Python,DynamoDB;Elasticsearch;MongoDB;PostgreSQL;Redis,DynamoDB;Redis,AWS;Google Cloud Platform,AWS,FastAPI;Flask,FastAPI;Flask,Hadoop;Keras;NumPy;Pandas,Apache Spark;Hadoop;Keras;NumPy;Pandas;TensorFlow,Ansible;Docker;Git;Terraform,Docker;Git;Kubernetes;Terraform,Android Studio;Eclipse;IntelliJ;IPython/Jupyte...,IntelliJ;IPython/Jupyter;Notepad++;Vim,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per week,Yes,I have never participated in Q&A on Stack Over...,"No, not really",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0
83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,3,"Developer, back-end",20 to 99 employees,CAD\tCanadian dollar,90000.0,Monthly,Bash/Shell;JavaScript;Node.js;Python,Go;Rust,Cassandra;Elasticsearch;MongoDB;PostgreSQL;Redis,NaN,Heroku,AWS;DigitalOcean,Django;Express;Flask;React.js,NaN,NumPy;Pandas;TensorFlow;Torch/PyTorch,NumPy;Pandas;TensorFlow;Torch/PyTorch,Ansible;Docker;Git;Terraform,Kubernetes;Terraform,PyCharm;Sublime Text,NaN,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0
83439,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,4,"Developer, front-end;Developer, full-stack;Dev...",I don’t know,BRL\tBrazilian real,7700.0,Monthly,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...,Oracle;PostgreSQL,Elasticsearch;MongoDB;MySQL;Oracle;PostgreSQL;...,Microsoft Azure,AWS,Angular;Spring,Express;Laravel;Spring;Symfony,NaN,NaN,Docker;Git,Docker;Git;Kubernetes,IntelliJ;Visual Studio Code,IntelliJ;PHPStorm;Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per week,Yes,A few times per week,"Yes, somewhat",No,18-24 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0

In [12]:
df.rename(columns={'ConvertedCompYearly': 'SalaryUS'}, inplace=True)

In [13]:
df['SOAccount'] = df['SOAccount'].map({'Yes':True, 'No':False}).head(10)

In [14]:
pd.set_option('display.max_rows', 48)
pd.set_option('display.max_columns', 6)

In [15]:
schema_df.head # to see the top five values .

<bound method NDFrame.head of                        qid                                           question  \
qname
S0                   QID16  <div><span style="font-size:19px;"><strong>Hel...
MetaInfo             QID12                                  Browser Meta Info
S1                    QID1  <span style="font-size:22px; font-family: aria...
MainBranch            QID2  Which of the following options best describes ...
Employment           QID24  Which of the following best describes your cur...
Country               QID6  Where do you live? <span style="font-weight: b...
US_State              QID7  <p>In which state or territory of the USA do y...
UK_Country            QID9  In which part of the United Kingdom do you liv...
S2                  QID190  <span style="font-size:22px; font-family: aria...
EdLevel              QID25  Which of the following best describes the high...
Age1stCode          QID149  At what age did you write your first line of c...
LearnCode           QID276  How did you learn to code? Select all that apply.
YearsCode            QID32  Including any education, how many years have y...
YearsCodePro         QID34  NOT including education, how many years have y...
DevType              QID31  Which of the following describes your current ...
OrgSize              QID29  Approximately how many people are employed by ...
Currency             QID50  Which currency do you use day-to-day? If your ...
CompTotal            QID51  What is your current total compensation (salar...
CompFreq             QID52   Is that compensation weekly, monthly, or yearly?
S3                   QID61  <span style="font-size:22px; font-family: aria...
Language            QID233  Which <b>programming, scripting, and markup la...
Database            QID262  Which <b>database environments </b>have you do...
Platform            QID263  Which <b>cloud platforms</b> have you done ext...
Webframe            QID264  Which <strong>web frameworks </strong><span st...
MiscTech            QID265  Which <b>other frameworks and libraries</b> ha...
ToolsTech           QID275  Which <strong>tools</strong> have you done ext...
NEWCollabTools      QID274  Which <strong>development environments</strong...
OpSys                QID71  What is the primary operating system in which ...
NEWStuck            QID243  What do you do when you get stuck on a problem...
S4                   QID91  <span style="font-size:22px; font-family: aria...
NEWSOSites          QID266  Which of the following Stack Overflow sites ha...
SOVisitFreq         QID100  How frequently would you say you visit Stack O...
SOAccount           QID101              Do you have a Stack Overflow account?
SOPartFreq          QID102  How frequently would you say you participate i...
SOComm              QID106  Do you consider yourself a member of the Stack...
NEWOtherComms       QID267  Are you a member of any other online developer...
NEWOtherCommsNames  QID268  Please name up to 5 other online developer com...
S5                  QID121  <span style="font-size:22px; font-family: aria...
Age                 QID127                                  What is your age?
Gender              QID122  Which of the following describe you, if any? P...
Trans               QID153                    Do you identify as transgender?
Sexuality           QID136  Which of the following describe you, if any? P...
Ethnicity           QID126  Which of the following describe you, if any? P...
Accessibility       QID124  Which of the following describe you, if any? P...
MentalHealth        QID125  Which of the following describe you, if any? P...
S6                  QID131  <span style="font-size:22px;"><strong>Final Qu...
SurveyLength        QID132  How do you feel about the length of the survey...
SurveyEase          QID133  How easy or difficult was this survey to compl...

                    force_resp    type selector
qname
S0                       False      DB       TB
MetaInfo                 False    Meta  Browser
S1                       False      DB       TB
MainBranch                True      MC     SAVR
Employment               False      MC     MAVR
Country                   True      MC       DL
US_State                 False      MC       DL
UK_Country               False      MC       DL
S2                       False      DB       TB
EdLevel                  False      MC     SAVR
Age1stCode               False      MC     MAVR
LearnCode                False      MC     MAVR
YearsCode                False      MC       DL
YearsCodePro             False      MC       DL
DevType                  False      MC     MAVR
OrgSize                  False      MC     MAVR
Currency                  True      MC       SB
CompTotal                False      TE       SL
CompFreq                 False      MC     MAVR
S3                       False      DB       TB
Language                 False  Matrix   Likert
Database                 False  Matrix   Likert
Platform                 False  Matrix   Likert
Webframe                 False  Matrix   Likert
MiscTech                 False  Matrix   Likert
ToolsTech                False  Matrix   Likert
NEWCollabTools           False  Matrix   Likert
OpSys                    False      MC     SAVR
NEWStuck                 False      MC     MAVR
S4                       False      DB       TB
NEWSOSites               False      MC     MAVR
SOVisitFreq              False      MC     MAVR
SOAccount                False      MC     MAVR
SOPartFreq               False      MC     MAVR
SOComm                   False      MC     MAVR
NEWOtherComms            False      MC     MAVR
NEWOtherCommsNames       False  Matrix   Likert
S5                       False      DB       TB
Age                      False      MC     MAVR
Gender                   False      MC     MAVR
Trans                    False      MC     MAVR
Sexuality                False      MC     MAVR
Ethnicity                False      MC     MAVR
Accessibility            False      MC     MAVR
MentalHealth             False      MC     MAVR
S6                       False      DB       TB
SurveyLength             False      MC     MAVR
SurveyEase               False      MC     MAVR  >

In [16]:
df.tail(10) # to see the last ten values .

,MainBranch,Employment,Country,...,SurveyLength,SurveyEase,SalaryUS
ResponseId,,,,,,,
83430,I code primarily as a hobby,"Not employed, but looking for work",United States of America,...,Appropriate in length,Neither easy nor difficult,NaN
83431,I am a developer by profession,Employed full-time,United States of America,...,Appropriate in length,Easy,125000.0
83432,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Pakistan,...,Appropriate in length,Easy,11676.0
83433,I am a developer by profession,Employed full-time,Canada,...,Appropriate in length,Easy,80169.0
83434,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Brazil,...,Appropriate in length,Easy,18326.0
83435,I am a developer by profession,Employed full-time,United States of America,...,Appropriate in length,Easy,160500.0
83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,...,Appropriate in length,Easy,3960.0
83437,I am a developer by profession,Employed full-time,United States of America,...,Appropriate in length,Neither easy nor difficult,90000.0
83438,I am a developer by profession,Employed full-time,Canada,...,Appropriate in length,Neither easy nor difficult,816816.0
83439,I am a developer by profession,Employed full-time,Brazil,...,Appropriate in length,Easy,21168.0

In [17]:
schema_df.head() # to print the first five rows 0:4 .

,qid,question,force_resp,type,selector
qname,,,,,
S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
MetaInfo,QID12,Browser Meta Info,False,Meta,Browser
S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
Employment,QID24,Which of the following best describes your cur...,False,MC,MAVR

In [18]:
df.columns # to print all the columns .

Index(['MainBranch', 'Employment', 'Country', 'US_State', 'UK_Country',
       'EdLevel', 'Age1stCode', 'LearnCode', 'YearsCode', 'YearsCodePro',
       'DevType', 'OrgSize', 'Currency', 'CompTotal', 'CompFreq',
       'LanguageHaveWorkedWith', 'LanguageWantToWorkWith',
       'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith',
       'PlatformHaveWorkedWith', 'PlatformWantToWorkWith',
       'WebframeHaveWorkedWith', 'WebframeWantToWorkWith',
       'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith',
       'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'OpSys',
       'NEWStuck', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'NEWOtherComms', 'Age', 'Gender', 'Trans', 'Sexuality',
       'Ethnicity', 'Accessibility', 'MentalHealth', 'SurveyLength',
       'SurveyEase', 'SalaryUS'],
      dtype='object')

In [19]:
df['LanguageHaveWorkedWith'].value_counts().head(7)# to print all value counts of a column .

Python                                    1337
HTML/CSS;JavaScript;Node.js;TypeScript     811
Java                                       715
HTML/CSS;JavaScript;PHP;SQL                674
C#                                         597
C#;HTML/CSS;JavaScript;SQL                 558
HTML/CSS;JavaScript                        531
Name: LanguageHaveWorkedWith, dtype: int64

In [20]:
df.loc[0:2, 'Employment':'UK_Country'] # Too print rows 0 to 2 and columns Employment to UK_Country .

,Employment,Country,US_State,UK_Country
ResponseId,,,,
1,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN
2,"Student, full-time",Netherlands,NaN,NaN

In [21]:
schema_df.loc['CompTotal', 'question'] # to print 'CompTotal' 's Question text .

'What is your current total compensation (salary, bonuses, and perks, before taxes and deductions), in ${q://QID50/ChoiceGroup/SelectedChoicesTextEntry}? Please enter a whole number in the box below, without any punctuation. If you are paid hourly, please estimate an equivalent weekly, monthly, or yearly salary. If you prefer not to answer, please leave the box empty.'

In [22]:
schema_df.sort_index(ascending=True) # to sort this by Alphabet | ascending is True .

,qid,question,force_resp,type,selector
qname,,,,,
Accessibility,QID124,"Which of the following describe you, if any? P...",False,MC,MAVR
Age,QID127,What is your age?,False,MC,MAVR
Age1stCode,QID149,At what age did you write your first line of c...,False,MC,MAVR
CompFreq,QID52,"Is that compensation weekly, monthly, or yearly?",False,MC,MAVR
CompTotal,QID51,What is your current total compensation (salar...,False,TE,SL
Country,QID6,"Where do you live? <span style=""font-weight: b...",True,MC,DL
Currency,QID50,Which currency do you use day-to-day? If your ...,True,MC,SB
Database,QID262,Which <b>database environments </b>have you do...,False,Matrix,Likert
DevType,QID31,Which of the following describes your current ...,False,MC,MAVR
EdLevel,QID25,Which of the following best describes the high...,False,MC,SAVR
Employment,QID24,Which of the following best describes your cur...,False,MC,MAVR
Ethnicity,QID126,"Which of the following describe you, if any? P...",False,MC,MAVR
Gender,QID122,"Which of the following describe you, if any? P...",False,MC,MAVR
Language,QID233,"Which <b>programming, scripting, and markup la...",False,Matrix,Likert
LearnCode,QID276,How did you learn to code? Select all that apply.,False,MC,MAVR
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
MentalHealth,QID125,"Which of the following describe you, if any? P...",False,MC,MAVR
MetaInfo,QID12,Browser Meta Info,False,Meta,Browser
MiscTech,QID265,Which <b>other frameworks and libraries</b> ha...,False,Matrix,Likert
NEWCollabTools,QID274,Which <strong>development environments</strong...,False,Matrix,Likert
NEWOtherComms,QID267,Are you a member of any other online developer...,False,MC,MAVR
NEWOtherCommsNames,QID268,Please name up to 5 other online developer com...,False,Matrix,Likert
NEWSOSites,QID266,Which of the following Stack Overflow sites ha...,False,MC,MAVR
NEWStuck,QID243,What do you do when you get stuck on a problem...,False,MC,MAVR
OpSys,QID71,What is the primary operating system in which ...,False,MC,SAVR
OrgSize,QID29,Approximately how many people are employed by ...,False,MC,MAVR
Platform,QID263,Which <b>cloud platforms</b> have you done ext...,False,Matrix,Likert
S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S2,QID190,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S3,QID61,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S4,QID91,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S5,QID121,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S6,QID131,"<span style=""font-size:22px;""><strong>Final Qu...",False,DB,TB
SOAccount,QID101,Do you have a Stack Overflow account?,False,MC,MAVR
SOComm,QID106,Do you consider yourself a member of the Stack...,False,MC,MAVR
SOPartFreq,QID102,How frequently would you say you participate i...,False,MC,MAVR
SOVisitFreq,QID100,How frequently would you say you visit Stack O...,False,MC,MAVR
Sexuality,QID136,"Which of the following describe you, if any? P...",False,MC,MAVR
SurveyEase,QID133,How easy or difficult was this survey to compl...,False,MC,MAVR
SurveyLength,QID132,How do you feel about the length of the survey...,False,MC,MAVR
ToolsTech,QID275,Which <strong>tools</strong> have you done ext...,False,Matrix,Likert
Trans,QID153,Do you identify as transgender?,False,MC,MAVR
UK_Country,QID9,In which part of the United Kingdom do you liv...,False,MC,DL
US_State,QID7,<p>In which state or territory of the USA do y...,False,MC,DL
Webframe,QID264,Which <strong>web frameworks </strong><span st...,False,Matrix,Likert
YearsCode,QID32,"Including any education, how many years have y...",False,MC,DL
YearsCodePro,QID34,"NOT including education, how many years have y...",False,MC,DL

In [23]:
schema_df.loc['YearsCode', 'question'] # to print 'YearsCode''s Question text .

'Including any education, how many years have you been coding in total?'

In [24]:
schema_df.sort_index(ascending=False) # to print in vise verca .

,qid,question,force_resp,type,selector
qname,,,,,
YearsCodePro,QID34,"NOT including education, how many years have y...",False,MC,DL
YearsCode,QID32,"Including any education, how many years have y...",False,MC,DL
Webframe,QID264,Which <strong>web frameworks </strong><span st...,False,Matrix,Likert
US_State,QID7,<p>In which state or territory of the USA do y...,False,MC,DL
UK_Country,QID9,In which part of the United Kingdom do you liv...,False,MC,DL
Trans,QID153,Do you identify as transgender?,False,MC,MAVR
ToolsTech,QID275,Which <strong>tools</strong> have you done ext...,False,Matrix,Likert
SurveyLength,QID132,How do you feel about the length of the survey...,False,MC,MAVR
SurveyEase,QID133,How easy or difficult was this survey to compl...,False,MC,MAVR
Sexuality,QID136,"Which of the following describe you, if any? P...",False,MC,MAVR
SOVisitFreq,QID100,How frequently would you say you visit Stack O...,False,MC,MAVR
SOPartFreq,QID102,How frequently would you say you participate i...,False,MC,MAVR
SOComm,QID106,Do you consider yourself a member of the Stack...,False,MC,MAVR
SOAccount,QID101,Do you have a Stack Overflow account?,False,MC,MAVR
S6,QID131,"<span style=""font-size:22px;""><strong>Final Qu...",False,DB,TB
S5,QID121,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S4,QID91,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S3,QID61,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S2,QID190,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
Platform,QID263,Which <b>cloud platforms</b> have you done ext...,False,Matrix,Likert
OrgSize,QID29,Approximately how many people are employed by ...,False,MC,MAVR
OpSys,QID71,What is the primary operating system in which ...,False,MC,SAVR
NEWStuck,QID243,What do you do when you get stuck on a problem...,False,MC,MAVR
NEWSOSites,QID266,Which of the following Stack Overflow sites ha...,False,MC,MAVR
NEWOtherCommsNames,QID268,Please name up to 5 other online developer com...,False,Matrix,Likert
NEWOtherComms,QID267,Are you a member of any other online developer...,False,MC,MAVR
NEWCollabTools,QID274,Which <strong>development environments</strong...,False,Matrix,Likert
MiscTech,QID265,Which <b>other frameworks and libraries</b> ha...,False,Matrix,Likert
MetaInfo,QID12,Browser Meta Info,False,Meta,Browser
MentalHealth,QID125,"Which of the following describe you, if any? P...",False,MC,MAVR
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
LearnCode,QID276,How did you learn to code? Select all that apply.,False,MC,MAVR
Language,QID233,"Which <b>programming, scripting, and markup la...",False,Matrix,Likert
Gender,QID122,"Which of the following describe you, if any? P...",False,MC,MAVR
Ethnicity,QID126,"Which of the following describe you, if any? P...",False,MC,MAVR
Employment,QID24,Which of the following best describes your cur...,False,MC,MAVR
EdLevel,QID25,Which of the following best describes the high...,False,MC,SAVR
DevType,QID31,Which of the following describes your current ...,False,MC,MAVR
Database,QID262,Which <b>database environments </b>have you do...,False,Matrix,Likert
Currency,QID50,Which currency do you use day-to-day? If your ...,True,MC,SB
Country,QID6,"Where do you live? <span style=""font-weight: b...",True,MC,DL
CompTotal,QID51,What is your current total compensation (salar...,False,TE,SL
CompFreq,QID52,"Is that compensation weekly, monthly, or yearly?",False,MC,MAVR
Age1stCode,QID149,At what age did you write your first line of c...,False,MC,MAVR
Age,QID127,What is your age?,False,MC,MAVR
Accessibility,QID124,"Which of the following describe you, if any? P...",False,MC,MAVR

In [25]:
schema_df.sort_index(inplace=True) # Schema_df.sort | inplace=True is neccessary .

In [26]:
schema_df

,qid,question,force_resp,type,selector
qname,,,,,
Accessibility,QID124,"Which of the following describe you, if any? P...",False,MC,MAVR
Age,QID127,What is your age?,False,MC,MAVR
Age1stCode,QID149,At what age did you write your first line of c...,False,MC,MAVR
CompFreq,QID52,"Is that compensation weekly, monthly, or yearly?",False,MC,MAVR
CompTotal,QID51,What is your current total compensation (salar...,False,TE,SL
Country,QID6,"Where do you live? <span style=""font-weight: b...",True,MC,DL
Currency,QID50,Which currency do you use day-to-day? If your ...,True,MC,SB
Database,QID262,Which <b>database environments </b>have you do...,False,Matrix,Likert
DevType,QID31,Which of the following describes your current ...,False,MC,MAVR
EdLevel,QID25,Which of the following best describes the high...,False,MC,SAVR
Employment,QID24,Which of the following best describes your cur...,False,MC,MAVR
Ethnicity,QID126,"Which of the following describe you, if any? P...",False,MC,MAVR
Gender,QID122,"Which of the following describe you, if any? P...",False,MC,MAVR
Language,QID233,"Which <b>programming, scripting, and markup la...",False,Matrix,Likert
LearnCode,QID276,How did you learn to code? Select all that apply.,False,MC,MAVR
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
MentalHealth,QID125,"Which of the following describe you, if any? P...",False,MC,MAVR
MetaInfo,QID12,Browser Meta Info,False,Meta,Browser
MiscTech,QID265,Which <b>other frameworks and libraries</b> ha...,False,Matrix,Likert
NEWCollabTools,QID274,Which <strong>development environments</strong...,False,Matrix,Likert
NEWOtherComms,QID267,Are you a member of any other online developer...,False,MC,MAVR
NEWOtherCommsNames,QID268,Please name up to 5 other online developer com...,False,Matrix,Likert
NEWSOSites,QID266,Which of the following Stack Overflow sites ha...,False,MC,MAVR
NEWStuck,QID243,What do you do when you get stuck on a problem...,False,MC,MAVR
OpSys,QID71,What is the primary operating system in which ...,False,MC,SAVR
OrgSize,QID29,Approximately how many people are employed by ...,False,MC,MAVR
Platform,QID263,Which <b>cloud platforms</b> have you done ext...,False,Matrix,Likert
S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S2,QID190,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S3,QID61,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S4,QID91,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S5,QID121,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S6,QID131,"<span style=""font-size:22px;""><strong>Final Qu...",False,DB,TB
SOAccount,QID101,Do you have a Stack Overflow account?,False,MC,MAVR
SOComm,QID106,Do you consider yourself a member of the Stack...,False,MC,MAVR
SOPartFreq,QID102,How frequently would you say you participate i...,False,MC,MAVR
SOVisitFreq,QID100,How frequently would you say you visit Stack O...,False,MC,MAVR
Sexuality,QID136,"Which of the following describe you, if any? P...",False,MC,MAVR
SurveyEase,QID133,How easy or difficult was this survey to compl...,False,MC,MAVR
SurveyLength,QID132,How do you feel about the length of the survey...,False,MC,MAVR
ToolsTech,QID275,Which <strong>tools</strong> have you done ext...,False,Matrix,Likert
Trans,QID153,Do you identify as transgender?,False,MC,MAVR
UK_Country,QID9,In which part of the United Kingdom do you liv...,False,MC,DL
US_State,QID7,<p>In which state or territory of the USA do y...,False,MC,DL
Webframe,QID264,Which <strong>web frameworks </strong><span st...,False,Matrix,Likert
YearsCode,QID32,"Including any education, how many years have y...",False,MC,DL
YearsCodePro,QID34,"NOT including education, how many years have y...",False,MC,DL

In [27]:
highest_salary = (df['SalaryUS'] > 90000)

In [28]:
df.loc[highest_salary, ['Country', 'Currency', 'LanguageHaveWorkedWith']].head(10)

,Country,Currency,LanguageHaveWorkedWith
ResponseId,,,
19,Singapore,SGD\tSingapore dollar,C++;Python
32,Israel,ILS\tIsraeli new shekel,Bash/Shell;Go;Java;Node.js;Python;Scala;SQL
37,United States of America,USD\tUnited States dollar,Assembly;C;Java;Kotlin;Rust
38,United States of America,USD\tUnited States dollar,Go
63,United States of America,USD\tUnited States dollar,C#;HTML/CSS;JavaScript;Node.js;PowerShell;Pyth...
65,United States of America,USD\tUnited States dollar,HTML/CSS;JavaScript;Python
70,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,HTML/CSS;JavaScript;SQL;TypeScript
76,United States of America,USD\tUnited States dollar,HTML/CSS;JavaScript;PHP
78,Canada,CAD\tCanadian dollar,HTML/CSS;Python;R
81,Uzbekistan,UZS\tUzbekistani som,HTML/CSS;JavaScript;Node.js

In [33]:
python_coder = (df['LanguageHaveWorkedWith'] == "Python") & (df['Country'] == "Germany")

In [30]:
df.loc[python_coder, ['Country', 'Currency', 'Sexuality', 'LanguageHaveWorkedWith', 'CompTotal']].head(10)

,Country,Currency,Sexuality,LanguageHaveWorkedWith,CompTotal
ResponseId,,,,,
796,Germany,NaN,Prefer not to say,Python,NaN
1644,Germany,EUR European Euro,Straight / Heterosexual,Python,NaN
3392,Germany,NaN,Straight / Heterosexual,Python,NaN
3425,Germany,EUR European Euro,Bisexual;Queer,Python,3465.0
4306,Germany,EUR European Euro,Straight / Heterosexual,Python,2800.0
4397,Germany,EUR European Euro,Straight / Heterosexual,Python,102000.0
5130,Germany,EUR European Euro,Straight / Heterosexual,Python,86000.0
5639,Germany,NaN,Prefer not to say,Python,NaN
5669,Germany,EUR European Euro,Straight / Heterosexual,Python,1000.0
6450,Germany,EUR European Euro,NaN,Python,84000.0

In [31]:
df[python_coder].value_counts()

Series([], dtype: int64)

In [32]:
df

,MainBranch,Employment,Country,...,SurveyLength,SurveyEase,SalaryUS
ResponseId,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,...,Appropriate in length,Easy,62268.0
2,I am a student who is learning to code,"Student, full-time",Netherlands,...,Appropriate in length,Easy,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,...,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,...,Appropriate in length,Neither easy nor difficult,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,...,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...
83435,I am a developer by profession,Employed full-time,United States of America,...,Appropriate in length,Easy,160500.0
83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,...,Appropriate in length,Easy,3960.0
83437,I am a developer by profession,Employed full-time,United States of America,...,Appropriate in length,Neither easy nor difficult,90000.0
83438,I am a developer by profession,Employed full-time,Canada,...,Appropriate in length,Neither easy nor difficult,816816.0
83439,I am a developer by profession,Employed full-time,Brazil,...,Appropriate in length,Easy,21168.0

In [32]:
schema_df

,qid,question,force_resp,type,selector
qname,,,,,
Accessibility,QID124,"Which of the following describe you, if any? P...",False,MC,MAVR
Age,QID127,What is your age?,False,MC,MAVR
Age1stCode,QID149,At what age did you write your first line of c...,False,MC,MAVR
CompFreq,QID52,"Is that compensation weekly, monthly, or yearly?",False,MC,MAVR
CompTotal,QID51,What is your current total compensation (salar...,False,TE,SL
Country,QID6,"Where do you live? <span style=""font-weight: b...",True,MC,DL
Currency,QID50,Which currency do you use day-to-day? If your ...,True,MC,SB
Database,QID262,Which <b>database environments </b>have you do...,False,Matrix,Likert
DevType,QID31,Which of the following describes your current ...,False,MC,MAVR
EdLevel,QID25,Which of the following best describes the high...,False,MC,SAVR
Employment,QID24,Which of the following best describes your cur...,False,MC,MAVR
Ethnicity,QID126,"Which of the following describe you, if any? P...",False,MC,MAVR
Gender,QID122,"Which of the following describe you, if any? P...",False,MC,MAVR
Language,QID233,"Which <b>programming, scripting, and markup la...",False,Matrix,Likert
LearnCode,QID276,How did you learn to code? Select all that apply.,False,MC,MAVR
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
MentalHealth,QID125,"Which of the following describe you, if any? P...",False,MC,MAVR
MetaInfo,QID12,Browser Meta Info,False,Meta,Browser
MiscTech,QID265,Which <b>other frameworks and libraries</b> ha...,False,Matrix,Likert
NEWCollabTools,QID274,Which <strong>development environments</strong...,False,Matrix,Likert
NEWOtherComms,QID267,Are you a member of any other online developer...,False,MC,MAVR
NEWOtherCommsNames,QID268,Please name up to 5 other online developer com...,False,Matrix,Likert
NEWSOSites,QID266,Which of the following Stack Overflow sites ha...,False,MC,MAVR
NEWStuck,QID243,What do you do when you get stuck on a problem...,False,MC,MAVR
OpSys,QID71,What is the primary operating system in which ...,False,MC,SAVR
OrgSize,QID29,Approximately how many people are employed by ...,False,MC,MAVR
Platform,QID263,Which <b>cloud platforms</b> have you done ext...,False,Matrix,Likert
S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S2,QID190,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S3,QID61,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S4,QID91,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S5,QID121,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S6,QID131,"<span style=""font-size:22px;""><strong>Final Qu...",False,DB,TB
SOAccount,QID101,Do you have a Stack Overflow account?,False,MC,MAVR
SOComm,QID106,Do you consider yourself a member of the Stack...,False,MC,MAVR
SOPartFreq,QID102,How frequently would you say you participate i...,False,MC,MAVR
SOVisitFreq,QID100,How frequently would you say you visit Stack O...,False,MC,MAVR
Sexuality,QID136,"Which of the following describe you, if any? P...",False,MC,MAVR
SurveyEase,QID133,How easy or difficult was this survey to compl...,False,MC,MAVR
SurveyLength,QID132,How do you feel about the length of the survey...,False,MC,MAVR
ToolsTech,QID275,Which <strong>tools</strong> have you done ext...,False,Matrix,Likert
Trans,QID153,Do you identify as transgender?,False,MC,MAVR
UK_Country,QID9,In which part of the United Kingdom do you liv...,False,MC,DL
US_State,QID7,<p>In which state or territory of the USA do y...,False,MC,DL
Webframe,QID264,Which <strong>web frameworks </strong><span st...,False,Matrix,Likert
YearsCode,QID32,"Including any education, how many years have y...",False,MC,DL
YearsCodePro,QID34,"NOT including education, how many years have y...",False,MC,DL

In [33]:
df.sort_values(by=['Country', 'SalaryUS'], inplace=True, ascending=[True,False])

In [34]:
df[['Country', 'SalaryUS']].head(10)

                Country    SalaryUS
ResponseId
65400       Afghanistan  30468516.0
22667       Afghanistan    155496.0
27199       Afghanistan     51804.0
31087       Afghanistan     23964.0
44641       Afghanistan     15132.0
11378       Afghanistan      9792.0
17487       Afghanistan      5448.0
51429       Afghanistan      4668.0
14883       Afghanistan      4200.0
17121       Afghanistan      3108.0

In [35]:
df['SalaryUS'].nlargest(10)

ResponseId
66911    45241312.0
65400    30468516.0
40587    21822250.0
28792    20000000.0
12701    19200000.0
9609     17500000.0
5306     15000000.0
12904    14411628.0
66489    12750000.0
7206     12500000.0
Name: SalaryUS, dtype: float64

In [36]:
python = [df.nlargest(10, 'SalaryUS'), df['LanguageHaveWorkedWith']]

In [37]:
python

[                                                   MainBranch  \
 ResponseId
 66911                          I am a developer by profession
 65400                          I am a developer by profession
 40587                          I am a developer by profession
 28792                          I am a developer by profession
 12701                          I am a developer by profession
 9609        I am not primarily a developer, but I write co...
 5306                           I am a developer by profession
 12904                          I am a developer by profession
 66489                          I am a developer by profession
 7206                           I am a developer by profession

                                                    Employment  \
 ResponseId
 66911                                     I prefer not to say
 65400                                      Employed full-time
 40587                                      Employed full-time
 28792                                      Employed full-time
 12701                                      Employed full-time
 9609                                       Employed full-time
 5306        Independent contractor, freelancer, or self-em...
 12904                                      Employed full-time
 66489                                      Employed full-time
 7206        Independent contractor, freelancer, or self-em...

                              Country  ...           SurveyLength  \
 ResponseId                            ...
 66911                        Belgium  ...              Too short
 65400                    Afghanistan  ...              Too short
 40587       United States of America  ...  Appropriate in length
 28792                          India  ...  Appropriate in length
 12701                          India  ...  Appropriate in length
 9609        United States of America  ...  Appropriate in length
 5306        United States of America  ...               Too long
 12904                         Serbia  ...               Too long
 66489       United States of America  ...  Appropriate in length
 7206        United States of America  ...  Appropriate in length

                             SurveyEase    SalaryUS
 ResponseId
 66911                              NaN  45241312.0
 65400                        Difficult  30468516.0
 40587                             Easy  21822250.0
 28792                             Easy  20000000.0
 12701                             Easy  19200000.0
 9609                              Easy  17500000.0
 5306                              Easy  15000000.0
 12904       Neither easy nor difficult  14411628.0
 66489                             Easy  12750000.0
 7206                              Easy  12500000.0

 [10 rows x 47 columns],
 ResponseId
 65400    Bash/Shell;C++;Elixir;LISP;Node.js;Ruby;Rust;S...
 22667                       Assembly;C#;C++;JavaScript;VBA
 27199                                 Go;JavaScript;Python
 31087              HTML/CSS;JavaScript;Node.js;PHP;SQL;VBA
 44641                       C#;HTML/CSS;JavaScript;PHP;SQL
                                ...
 75694                                               Python
 76083                      C++;Dart;Java;JavaScript;Python
 79302                                                  NaN
 80997                   HTML/CSS;JavaScript;Node.js;Python
 82407                             C#;JavaScript;PHP;Python
 Name: LanguageHaveWorkedWith, Length: 83439, dtype: object]

In [38]:
df['SalaryUS'].head(10)

ResponseId
65400    30468516.0
22667      155496.0
27199       51804.0
31087       23964.0
44641       15132.0
11378        9792.0
17487        5448.0
51429        4668.0
14883        4200.0
17121        3108.0
Name: SalaryUS, dtype: float64

In [39]:
df['SalaryUS'].median() # the median value of all of those

56211.0

In [40]:
df.median()

CompTotal    67000.0
SOAccount        1.0
SalaryUS     56211.0
dtype: float64

In [41]:
df.describe()

          CompTotal      SalaryUS
count  4.718300e+04  4.684400e+04
mean   2.119407e+69  1.184262e+05
std    4.603702e+71  5.272944e+05
min    0.000000e+00  1.000000e+00
25%    1.600000e+04  2.702500e+04
50%    6.700000e+04  5.621100e+04
75%    1.400000e+05  1.000000e+05
max    1.000000e+74  4.524131e+07

In [42]:
df['CompTotal'].count()

47183

In [43]:
df['Employment']

ResponseId
65400                                   Employed full-time
22667    Independent contractor, freelancer, or self-em...
27199    Independent contractor, freelancer, or self-em...
31087                                   Employed full-time
44641                                   Employed full-time
                               ...
75694                                   Student, full-time
76083                   Not employed, but looking for work
79302                                   Student, part-time
80997               Not employed, and not looking for work
82407                                   Employed part-time
Name: Employment, Length: 83439, dtype: object

In [44]:
df['Employment'].value_counts()

Employed full-time                                      53584
Student, full-time                                      11781
Independent contractor, freelancer, or self-employed     8041
Not employed, but looking for work                       2961
Employed part-time                                       2461
Student, part-time                                       2051
Not employed, and not looking for work                   1228
I prefer not to say                                       890
Retired                                                   326
Name: Employment, dtype: int64

In [49]:
schema_df.loc['LearnCode', 'question']

'How did you learn to code? Select all that apply.'

In [52]:
df['LearnCode'].value_counts(normalize=True).head(5)

School                                                                           0.087292
Other online resources (ex: videos, blogs, etc)                                  0.042212
Books / Physical media                                                           0.040464
School;Books / Physical media                                                    0.037800
Other online resources (ex: videos, blogs, etc);School;Books / Physical media    0.029423
Name: LearnCode, dtype: float64

In [57]:
df['Country'].value_counts().head()

United States of America                                15288
India                                                   10511
Germany                                                  5625
United Kingdom of Great Britain and Northern Ireland     4475
Canada                                                   3012
Name: Country, dtype: int64

In [58]:
country_grp = df.groupby(['Country'])

In [60]:
country_grp.get_group('Canada')

,MainBranch,Employment,Country,...,SurveyLength,SurveyEase,SalaryUS
ResponseId,,,,,,,
25103,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Canada,...,Too long,Easy,7563129.0
59555,"I am not primarily a developer, but I write co...",Employed full-time,Canada,...,Appropriate in length,Easy,5294200.0
62514,I am a developer by profession,Employed full-time,Canada,...,Appropriate in length,Neither easy nor difficult,5000000.0
21841,I am a developer by profession,Employed full-time,Canada,...,Appropriate in length,Neither easy nor difficult,4916050.0
54794,I am a developer by profession,Employed full-time,Canada,...,Appropriate in length,Neither easy nor difficult,4462250.0
...,...,...,...,...,...,...,...
83194,"I used to be a developer by profession, but no...",Employed full-time,Canada,...,Too long,Easy,NaN
83202,"I used to be a developer by profession, but no...",Employed full-time,Canada,...,Appropriate in length,Easy,NaN
83221,I am a developer by profession,"Student, full-time",Canada,...,Appropriate in length,Easy,NaN
83250,I am a developer by profession,"Not employed, and not looking for work",Canada,...,Appropriate in length,Easy,NaN
83270,I am a student who is learning to code,"Student, full-time",Canada,...,Appropriate in length,Neither easy nor difficult,NaN

In [85]:
filt = df['Country'] == 'Russian Federation'

In [87]:
df.loc[filt]['Employment'].value_counts(normalize=True)

Employed full-time                                      0.682313
Independent contractor, freelancer, or self-employed    0.110204
Student, full-time                                      0.074830
Not employed, but looking for work                      0.038095
Employed part-time                                      0.031293
Student, part-time                                      0.030612
Not employed, and not looking for work                  0.017007
I prefer not to say                                     0.012245
Retired                                                 0.003401
Name: Employment, dtype: float64

In [91]:
country_grp['Employment'].value_counts(normalize=True).loc['Canada']

Employment
Employed full-time                                      0.647723
Student, full-time                                      0.157527
Independent contractor, freelancer, or self-employed    0.090728
Not employed, but looking for work                      0.029578
Not employed, and not looking for work                  0.021934
Employed part-time                                      0.018611
Student, part-time                                      0.013958
I prefer not to say                                     0.012629
Retired                                                 0.007311
Name: Employment, dtype: float64

In [94]:
country_grp['SalaryUS'].median().loc['Germany']

64859.0

In [96]:
country_grp['SalaryUS'].agg(['median', 'mean']).loc['Canada']

median     75631.000000
mean      135732.563006
Name: Canada, dtype: float64

In [102]:
filt = df['Country'] == 'Canada'
df.loc[filt]['LanguageHaveWorkedWith'].str.contains('Python').sum()

1593

In [104]:
country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              20
Albania                                  30
Algeria                                  19
Andorra                                   4
Angola                                    5
                                       ...
Venezuela, Bolivarian Republic of...     43
Viet Nam                                173
Yemen                                     6
Zambia                                   12
Zimbabwe                                 17
Name: LanguageHaveWorkedWith, Length: 181, dtype: int64

In [34]:
python_coder

ResponseId
1        False
2        False
3        False
4        False
5        False
         ...
83435    False
83436    False
83437    False
83438    False
83439    False
Length: 83439, dtype: bool