In [1]:
import pandas as pd

In [51]:
df = pd.read_csv('data/survey_results_public.csv', index_col='ResponseId')
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col='qname')

In [8]:
schema_df

,qid,question,force_resp,type,selector
qname,,,,,
S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
MetaInfo,QID12,Browser Meta Info,False,Meta,Browser
S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
Employment,QID24,Which of the following best describes your cur...,False,MC,MAVR
Country,QID6,"Where do you live? <span style=""font-weight: b...",True,MC,DL
US_State,QID7,<p>In which state or territory of the USA do y...,False,MC,DL
UK_Country,QID9,In which part of the United Kingdom do you liv...,False,MC,DL
S2,QID190,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
EdLevel,QID25,Which of the following best describes the high...,False,MC,SAVR
Age1stCode,QID149,At what age did you write your first line of c...,False,MC,MAVR
LearnCode,QID276,How did you learn to code? Select all that apply.,False,MC,MAVR
YearsCode,QID32,"Including any education, how many years have y...",False,MC,DL
YearsCodePro,QID34,"NOT including education, how many years have y...",False,MC,DL
DevType,QID31,Which of the following describes your current ...,False,MC,MAVR
OrgSize,QID29,Approximately how many people are employed by ...,False,MC,MAVR
Currency,QID50,Which currency do you use day-to-day? If your ...,True,MC,SB
CompTotal,QID51,What is your current total compensation (salar...,False,TE,SL
CompFreq,QID52,"Is that compensation weekly, monthly, or yearly?",False,MC,MAVR
S3,QID61,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
Language,QID233,"Which <b>programming, scripting, and markup la...",False,Matrix,Likert
Database,QID262,Which <b>database environments </b>have you do...,False,Matrix,Likert
Platform,QID263,Which <b>cloud platforms</b> have you done ext...,False,Matrix,Likert
Webframe,QID264,Which <strong>web frameworks </strong><span st...,False,Matrix,Likert
MiscTech,QID265,Which <b>other frameworks and libraries</b> ha...,False,Matrix,Likert
ToolsTech,QID275,Which <strong>tools</strong> have you done ext...,False,Matrix,Likert
NEWCollabTools,QID274,Which <strong>development environments</strong...,False,Matrix,Likert
OpSys,QID71,What is the primary operating system in which ...,False,MC,SAVR
NEWStuck,QID243,What do you do when you get stuck on a problem...,False,MC,MAVR
S4,QID91,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
NEWSOSites,QID266,Which of the following Stack Overflow sites ha...,False,MC,MAVR
SOVisitFreq,QID100,How frequently would you say you visit Stack O...,False,MC,MAVR
SOAccount,QID101,Do you have a Stack Overflow account?,False,MC,MAVR
SOPartFreq,QID102,How frequently would you say you participate i...,False,MC,MAVR
SOComm,QID106,Do you consider yourself a member of the Stack...,False,MC,MAVR
NEWOtherComms,QID267,Are you a member of any other online developer...,False,MC,MAVR
NEWOtherCommsNames,QID268,Please name up to 5 other online developer com...,False,Matrix,Likert
S5,QID121,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
Age,QID127,What is your age?,False,MC,MAVR
Gender,QID122,"Which of the following describe you, if any? P...",False,MC,MAVR
Trans,QID153,Do you identify as transgender?,False,MC,MAVR
Sexuality,QID136,"Which of the following describe you, if any? P...",False,MC,MAVR
Ethnicity,QID126,"Which of the following describe you, if any? P...",False,MC,MAVR
Accessibility,QID124,"Which of the following describe you, if any? P...",False,MC,MAVR
MentalHealth,QID125,"Which of the following describe you, if any? P...",False,MC,MAVR
S6,QID131,"<span style=""font-size:22px;""><strong>Final Qu...",False,DB,TB
SurveyLength,QID132,How do you feel about the length of the survey...,False,MC,MAVR
SurveyEase,QID133,How easy or difficult was this survey to compl...,False,MC,MAVR

In [9]:
df.shape

(83439, 47)

In [10]:
df.info

<bound method DataFrame.info of                                                    MainBranch  \
ResponseId
1                              I am a developer by profession
2                      I am a student who is learning to code
3           I am not primarily a developer, but I write co...
4                              I am a developer by profession
5                              I am a developer by profession
...                                                       ...
83435                          I am a developer by profession
83436                          I am a developer by profession
83437                          I am a developer by profession
83438                          I am a developer by profession
83439                          I am a developer by profession

                                                   Employment  \
ResponseId
1           Independent contractor, freelancer, or self-em...
2                                          Student, full-time
3                                          Student, full-time
4                                          Employed full-time
5           Independent contractor, freelancer, or self-em...
...                                                       ...
83435                                      Employed full-time
83436       Independent contractor, freelancer, or self-em...
83437                                      Employed full-time
83438                                      Employed full-time
83439                                      Employed full-time

                                                      Country    US_State  \
ResponseId
1                                                    Slovakia         NaN
2                                                 Netherlands         NaN
3                                          Russian Federation         NaN
4                                                     Austria         NaN
5           United Kingdom of Great Britain and Northern I...         NaN
...                                                       ...         ...
83435                                United States of America       Texas
83436                                                   Benin         NaN
83437                                United States of America  New Jersey
83438                                                  Canada         NaN
83439                                                  Brazil         NaN

           UK_Country                                            EdLevel  \
ResponseId
1                 NaN  Secondary school (e.g. American high school, G...
2                 NaN       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
3                 NaN       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4                 NaN    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
5             England    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
...               ...                                                ...
83435             NaN       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
83436             NaN       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
83437             NaN  Secondary school (e.g. American high school, G...
83438             NaN       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
83439             NaN                 Professional degree (JD, MD, etc.)

               Age1stCode                                          LearnCode  \
ResponseId
1           18 - 24 years  Coding Bootcamp;Other online resources (ex: vi...
2           11 - 17 years  Other online resources (ex: videos, blogs, etc...
3           11 - 17 years  Other online resources (ex: videos, blogs, etc...
4           11 - 17 years                                                NaN
5            5 - 10 years                            Friend or family member
...                   ...                                                ...
83435       11 - 17 years  Other online resources (ex: videos, blogs, etc...
83436       11 - 17 years  Other online resources (ex: videos, blogs, etc...
83437       11 - 17 years                                             School
83438       11 - 17 years  Online Courses or Certification;Books / Physic...
83439       11 - 17 years                                             School

           YearsCode YearsCodePro  ...              Age Gender Trans  \
ResponseId                         ...
1                NaN          NaN  ...  25-34 years old    Man    No
2                  7          NaN  ...  18-24 years old    Man    No
3                NaN          NaN  ...  18-24 years old    Man    No
4                NaN          NaN  ...  35-44 years old    Man    No
5                 17           10  ...  25-34 years old    Man    No
...              ...          ...  ...              ...    ...   ...
83435              6            5  ...  25-34 years old    Man    No
83436              4            2  ...  18-24 years old    Man    No
83437             10            4  ...  25-34 years old    Man    No
83438              5            3  ...  25-34 years old    Man    No
83439             14            4  ...  18-24 years old    Man    No

                          Sexuality                     Ethnicity  \
ResponseId
1           Straight / Heterosexual  White or of European descent
2           Straight / Heterosexual  White or of European descent
3                 Prefer not to say             Prefer not to say
4           Straight / Heterosexual  White or of European descent
5                               NaN  White or of European descent
...                             ...                           ...
83435       Straight / Heterosexual  White or of European descent
83436       Straight / Heterosexual   Black or of African descent
83437                           NaN  White or of European descent
83438       Straight / Heterosexual  White or of European descent
83439       Straight / Heterosexual        Hispanic or Latino/a/x

                          Accessibility  \
ResponseId
1                     None of the above
2                     None of the above
3                     None of the above
4           I am deaf / hard of hearing
5                     None of the above
...                                 ...
83435                 None of the above
83436                 None of the above
83437                 None of the above
83438                 None of the above
83439                 None of the above

                                                 MentalHealth  \
ResponseId
1                                           None of the above
2                                           None of the above
3                                           None of the above
4                                                         NaN
5                                                         NaN
...                                                       ...
83435       I have a concentration and/or memory disorder ...
83436                                       None of the above
83437                                       None of the above
83438       I have a mood or emotional disorder (e.g. depr...
83439                                       None of the above

                     SurveyLength                  SurveyEase  \
ResponseId
1           Appropriate in length                        Easy
2           Appropriate in length                        Easy
3           Appropriate in length                        Easy
4           Appropriate in length  Neither easy nor difficult
5           Appropriate in length                        Easy
...                           ...                         ...
83435       Appropriate in length                        Easy
83436       Appropriate in length                        Easy
83437       Appropriate in length  Neither easy nor difficult
83438       Appropriate in length  Neither easy nor difficult
83439       Appropriate in length                        Easy

           ConvertedCompYearly
ResponseId
1                      62268.0
2                          NaN
3                          NaN
4                          NaN
5                          NaN
...                        ...
83435                 160500.0
83436                   3960.0
83437                  90000.0
83438                 816816.0
83439                  21168.0

[83439 rows x 47 columns]>

In [12]:
pd.set_option('display.max_columns', 48)
pd.set_option('display.max_rows', 6)

In [16]:
schema_df.tail(5)

,qid,question,force_resp,type,selector
qname,,,,,
Accessibility,QID124,"Which of the following describe you, if any? P...",False,MC,MAVR
MentalHealth,QID125,"Which of the following describe you, if any? P...",False,MC,MAVR
S6,QID131,"<span style=""font-size:22px;""><strong>Final Qu...",False,DB,TB
SurveyLength,QID132,How do you feel about the length of the survey...,False,MC,MAVR
SurveyEase,QID133,How easy or difficult was this survey to compl...,False,MC,MAVR

In [17]:
df.columns

Index(['MainBranch', 'Employment', 'Country', 'US_State', 'UK_Country',
       'EdLevel', 'Age1stCode', 'LearnCode', 'YearsCode', 'YearsCodePro',
       'DevType', 'OrgSize', 'Currency', 'CompTotal', 'CompFreq',
       'LanguageHaveWorkedWith', 'LanguageWantToWorkWith',
       'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith',
       'PlatformHaveWorkedWith', 'PlatformWantToWorkWith',
       'WebframeHaveWorkedWith', 'WebframeWantToWorkWith',
       'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith',
       'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'OpSys',
       'NEWStuck', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'NEWOtherComms', 'Age', 'Gender', 'Trans', 'Sexuality',
       'Ethnicity', 'Accessibility', 'MentalHealth', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [22]:
df['Currency'].value_counts().head(5)

USD\tUnited States dollar    14363
EUR European Euro            13932
INR\tIndian rupee             6427
GBP\tPound sterling           3547
CAD\tCanadian dollar          2108
Name: Currency, dtype: int64

In [32]:
df.loc[0:5, "Country":"LearnCode"]

,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode
ResponseId,,,,,,
1,Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...
2,Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc..."
3,Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc..."
4,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN
5,United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member

In [42]:
schema_df.loc['Database', 'question']

'Which <b>database environments </b>have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the database and want to continue to do so, please check both boxes in that row.)'

In [50]:
schema_df.sort_index(ascending=True).head(5)

,qid,question,force_resp,type,selector
qname,,,,,
Accessibility,QID124,"Which of the following describe you, if any? P...",False,MC,MAVR
Age,QID127,What is your age?,False,MC,MAVR
Age1stCode,QID149,At what age did you write your first line of c...,False,MC,MAVR
CompFreq,QID52,"Is that compensation weekly, monthly, or yearly?",False,MC,MAVR
CompTotal,QID51,What is your current total compensation (salar...,False,TE,SL

In [52]:
people = {
    "first" : ["Tarokh", "James", "Tommy", "Max"],
    "last" : ["Yaghoubi", "white", "black", "amini"],
    "email":  ["tarokhgit@gmail.com", "james@gmail.com", "tommy@gmail.com", "max@outlook.com"]
}

In [53]:
pdf = pd.DataFrame(people)

In [54]:
pdf

    first      last                email
0  Tarokh  Yaghoubi  tarokhgit@gmail.com
1   James     white      james@gmail.com
2   Tommy     black      tommy@gmail.com
3     Max     amini      max@outlook.com